### ISSUE TITLE
[Bug] Selling Crashes the server.

### ISSUE THREAD

**Issue by AzureDoom** [AustereTony-MCMods/Oxygen-Merchants#3] opened 2019-08-12 20:21 UTC
Have currency set to coins with GrandEconomy installed. Crashes when trying to sell.
`java.lang.NoSuchMethodError: the_fireplace.grandeconomy.api.GrandEconomyApi.addToBalance(Ljava/util/UUID;JZ)V
	at austeretony.oxygen_cp_ge.common.main.GrandEconomyCurrencyProvider.addCurrency(GrandEconomyCurrencyProvider.java:33)
	at austeretony.oxygen.common.OxygenManagerServer.addCurrency(OxygenManagerServer.java:325)
	at austeretony.oxygen.common.currency.CurrencyHelperServer.addCurrency(CurrencyHelperServer.java:26)
	at austeretony.oxygen_merchants.common.main.OperationsProcessor.sell(OperationsProcessor.java:101)
	at austeretony.oxygen_merchants.common.main.OperationsProcessor.process(OperationsProcessor.java:55)
	at austeretony.oxygen_merchants.common.MerchantsManagerServer.runMerchantOperations(MerchantsManagerServer.java:69)
	at austeretony.oxygen_merchants.common.RunMerchantOperations.execute(RunMerchantOperations.java:19)
	at austeretony.oxygen.common.api.process.AbstractPersistentProcess.run(AbstractPersistentProcess.java:17)
	at austeretony.oxygen.common.ProcessesManagerServer.runServiceProcesses(ProcessesManagerServer.java:29)
	at austeretony.oxygen.common.ProcessesManagerServer.runProcesses(ProcessesManagerServer.java:67)
	at austeretony.oxygen.common.event.OxygenEventsServer.onServerTick(OxygenEventsServer.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_626_OxygenEventsServer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by AzureDoom** [comment] 2019-08-12 20:32
After running the `/oxygens currency --add -player AzureZhen -amount 200` command
`[15:31:25] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: oxygens currency --add -player AzureZhen -amount 200
java.lang.NoSuchMethodError: the_fireplace.grandeconomy.api.GrandEconomyApi.addToBalance(Ljava/util/UUID;JZ)V
	at austeretony.oxygen_cp_ge.common.main.GrandEconomyCurrencyProvider.addCurrency(GrandEconomyCurrencyProvider.java:33) ~[GrandEconomyCurrencyProvider.class:?]
	at austeretony.oxygen.common.OxygenManagerServer.addCurrency(OxygenManagerServer.java:325) ~[OxygenManagerServer.class:?]
	at austeretony.oxygen.common.currency.CurrencyHelperServer.addCurrency(CurrencyHelperServer.java:26) ~[CurrencyHelperServer.class:?]
	at austeretony.oxygen.common.command.CurrencyArgumentExecutorServer.execute(CurrencyArgumentExecutorServer.java:104) ~[CurrencyArgumentExecutorServer.class:?]
	at austeretony.oxygen.common.api.command.AbstractArgumentExecutor.process(AbstractArgumentExecutor.java:77) ~[AbstractArgumentExecutor.class:?]
	at austeretony.oxygen.common.api.command.AbstractOxygenCommand.func_184881_a(AbstractOxygenCommand.java:47) ~[AbstractOxygenCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by AustereTony-MCMods** [comment] 2019-09-10 17:07
Caused by changes in Grand Economy 1.2 API. Fixed in 0.8.1b.

**Closed as completed by AustereTony-MCMods** 2019-09-10 17:07 UTC
